export const FAVORITE_TYPES = {
  SITES: 'SITES',
  ARTICLES: 'ARTICLES',
  INSPIRATIONS: 'INSPIRATIONS',
  TOOLS: 'TOOLS',
  TUTORIALS: 'TUTORIALS',
} as const;

export const FAVORITE_TYPE_LABELS = {
  [FAVORITE_TYPES.SITES]: 'Sites',
  [FAVORITE_TYPES.ARTICLES]: 'Articles',
  [FAVORITE_TYPES.INSPIRATIONS]: 'Inspirations',
  [FAVORITE_TYPES.TOOLS]: 'Tools',
  [FAVORITE_TYPES.TUTORIALS]: 'Tutorials',
};
